# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x63\x61\x63he.proto\x12\x05\x63\x61\x63he"8\n\x08\x43\x61\x63heKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x0e\n\x06writer\x18\x03 \x01(\x04"Z\n\nCacheEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0f\n\x07\x65xpires\x18\x03 \x01(\x01\x12\x0f\n\x07version\x18\x04 \x01(\x04\x12\x0e\n\x06writer\x18\x05 \x01(\x04"-\n\nCacheClear\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x0e\n\x06writer\x18\x02 \x01(\x04";\n\nCacheValue\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0f\n\x07replica\x18\x03 \x01(\t",\n\x0b\x43\x61\x63heResult\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x0f\n\x07replica\x18\x02 \x01(\t"\'\n\x11\x43\x61\x63heStatsRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x04"\x84\x01\n\nCacheStats\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x0f\n\x07replica\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\x04\x12\x0f\n\x07\x65ntries\x18\x04 \x01(\x04\x12\x0e\n\x06writes\x18\x05 \x01(\x04\x12\r\n\x05reads\x18\x06 \x01(\x04\x12\x0c\n\x04hits\x18\x07 \x01(\x04\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "cache_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CACHEKEY._serialized_start = 22
    _CACHEKEY._serialized_end = 78
    _CACHEENTRY._serialized_start = 80
    _CACHEENTRY._serialized_end = 170
    _CACHECLEAR._serialized_start = 172
    _CACHECLEAR._serialized_end = 217
    _CACHEVALUE._serialized_start = 219
    _CACHEVALUE._serialized_end = 278
    _CACHERESULT._serialized_start = 280
    _CACHERESULT._serialized_end = 324
    _CACHESTATSREQUEST._serialized_start = 326
    _CACHESTATSREQUEST._serialized_end = 365
    _CACHESTATS._serialized_start = 368
    _CACHESTATS._serialized_end = 500
# @@protoc_insertion_point(module_scope)
