# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x61udio.proto\x12\x05\x61udio"`\n\nAudioFrame\x12\x13\n\x0bparticipant\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x03 \x01(\t\x12\x0b\n\x03pcm\x18\x04 \x01(\x0c\x12\x13\n\x0b\x63\x61ptured_at\x18\x05 \x01(\x01"\x86\x01\n\x0e\x41udioProcessed\x12\x13\n\x0bparticipant\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0b\n\x03pcm\x18\x03 \x01(\x0c\x12\x10\n\x08spectrum\x18\x04 \x01(\x0c\x12\x0e\n\x06worker\x18\x05 \x01(\t\x12\x0e\n\x06micros\x18\x06 \x01(\r\x12\x13\n\x0b\x63\x61ptured_at\x18\x07 \x01(\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "audio_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _AUDIOFRAME._serialized_start = 22
    _AUDIOFRAME._serialized_end = 118
    _AUDIOPROCESSED._serialized_start = 121
    _AUDIOPROCESSED._serialized_end = 255
# @@protoc_insertion_point(module_scope)
