# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cstream.proto\x12\x06stream"M\n\x06Prompt\x12\x11\n\tstream_id\x18\x01 \x01(\x04\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x0e\n\x06tokens\x18\x03 \x01(\r\x12\x10\n\x08\x66rom_seq\x18\x04 \x01(\r"C\n\x05Token\x12\x11\n\tstream_id\x18\x01 \x01(\x04\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0c\n\x04last\x18\x04 \x01(\x08"r\n\tGenerated\x12\x11\n\tstream_id\x18\x01 \x01(\x04\x12\x0e\n\x06tokens\x18\x02 \x01(\r\x12\x0f\n\x07seconds\x18\x03 \x01(\x01\x12\x0e\n\x06worker\x18\x04 \x01(\t\x12\x11\n\tcancelled\x18\x05 \x01(\x08\x12\x0e\n\x06resent\x18\x06 \x01(\r"@\n\x06Resume\x12\x11\n\tstream_id\x18\x01 \x01(\x04\x12\x10\n\x08\x66rom_seq\x18\x02 \x01(\r\x12\x11\n\tuntil_seq\x18\x03 \x01(\r":\n\x07Resumed\x12\x11\n\tstream_id\x18\x01 \x01(\x04\x12\x0e\n\x06resent\x18\x02 \x01(\r\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08"\x1b\n\x06\x43\x61ncel\x12\x11\n\tstream_id\x18\x01 \x01(\x04\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "stream_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PROMPT._serialized_start = 24
    _PROMPT._serialized_end = 101
    _TOKEN._serialized_start = 103
    _TOKEN._serialized_end = 170
    _GENERATED._serialized_start = 172
    _GENERATED._serialized_end = 286
    _RESUME._serialized_start = 288
    _RESUME._serialized_end = 352
    _RESUMED._serialized_start = 354
    _RESUMED._serialized_end = 412
    _CANCEL._serialized_start = 414
    _CANCEL._serialized_end = 441
# @@protoc_insertion_point(module_scope)
