#!/bin/sh
# Writes the system rules file into a C++ source, as the text mxcontrol's
# generate_rules writes: `sh embed_rules.sh RULES OUT.cc`, from the BUILD
# file's genrule and the Makefile alike. A raw string literal holds the
# text as it is; a file that contains the literal's end is refused rather
# than cut short.
set -eu
rules="$1"
out="$2"
if grep -q ')mxrules"' "$rules"; then
  echo "embed_rules.sh: $rules contains )mxrules\", which would end the string early" >&2
  exit 1
fi
{
  echo '// Generated by mxcontrol/embed_rules.sh from the system rules file; do not edit.'
  echo 'namespace mxcontrol {'
  echo 'extern const char kSystemRules[];'
  printf '%s' 'const char kSystemRules[] = R"mxrules('
  cat "$rules"
  echo ')mxrules";'
  echo '}  // namespace mxcontrol'
} > "$out"
