"""The building blocks of the step-by-step pictures: columns of boxes,
arrows between them, steps that highlight some arrows, sections and pages.
Page.render() produces the Markdown with one Mermaid frame per step.
pages.py declares the pictures; generate.py writes the files.

Each picture is fixed: columns of boxes with every arrow drawn in every
frame. A frame highlights the arrows of one step. Keeping topology and steps
in data, rather than in hand-edited Mermaid blocks, means the frames cannot
drift from one another.
"""

from dataclasses import dataclass, field


GREY = "stroke:#a0a0a0,stroke-width:1px"
ACTIVE = "stroke:#d62828,stroke-width:3px"
NODE_ACTIVE = "fill:#fde8e8,stroke:#d62828,stroke-width:2px"


@dataclass
class Column:
    """One column of boxes: a title and (id, label) pairs."""

    title: str
    nodes: list  # (id, label)


@dataclass
class Edge:
    """One arrow, from node id to node id, with its label."""

    src: str
    dst: str
    label: str


@dataclass
class Step:
    """One frame: a title, its explanation, the arrows it highlights (indices
    into the section's edges) and the boxes it emphasises (node ids)."""

    title: str
    text: str
    edges: list  # indices into Section.edges
    nodes: list = field(default_factory=list)  # node ids to emphasise


@dataclass
class Section:
    """One picture with its steps; a page holds one or more.

    Layout rule of thumb: Mermaid ranks nodes left to right by walking the
    arrows depth first, and a node with arrows to and from two nodes of the
    previous column pulls one of them out of its column. Draw at most one
    return path per right-hand node, and put the topology-only "connected"
    arrows in the forward direction.
    """

    title: str
    intro: str
    columns: list
    edges: list
    steps: list
    outro: str = ""

    def frame(self, step):
        """The Mermaid block for one step: every arrow, the step's in red."""
        lines = ["graph LR"]
        for i, col in enumerate(self.columns):
            lines.append("  subgraph col%d [%s]" % (i, col.title))
            for node_id, label in col.nodes:
                lines.append("    %s[%s]" % (node_id, label))
            lines.append("  end")
        for e in self.edges:
            lines.append('  %s -- "%s" --> %s' % (e.src, e.label, e.dst))
        lines.append("  linkStyle default " + GREY)
        if step.edges:
            lines.append("  linkStyle %s %s" % (",".join(str(i) for i in step.edges), ACTIVE))
        for node_id in step.nodes:
            lines.append("  style %s %s" % (node_id, NODE_ACTIVE))
        return "\n".join(lines)

    def markdown(self, heading):
        """The section as Markdown: intro, one heading and frame per step, outro."""
        out = ["%s %s" % (heading, self.title), "", self.intro.strip(), ""]
        for n, step in enumerate(self.steps, 1):
            out += [
                "%s# %d. %s" % (heading, n, step.title),
                "",
                step.text.strip(),
                "",
                "```mermaid",
                self.frame(step),
                "```",
                "",
            ]
        if self.outro:
            out += [self.outro.strip(), ""]
        return out


@dataclass
class Page:
    """One docs page: the file it becomes, a title, an intro, its sections
    and an outro; markdown() renders the whole page."""

    file: str
    title: str
    intro: str
    sections: list
    outro: str = ""

    def markdown(self):
        """The whole page as Markdown."""
        out = ["# %s" % self.title, "", self.intro.strip(), ""]
        for section in self.sections:
            out += section.markdown("##")
        if self.outro:
            out += [self.outro.strip(), ""]
        out += ["<!-- generated by docs/diagrams/generate.py; edit that file, not this one -->", ""]
        return "\n".join(out)
