# Python helpers used by the client library and the logging module.
py_library(
    name = "timer",
    srcs = ["timer.py"],
    imports = ["../.."],
    visibility = ["//multiplexer:__pkg__"],
)

py_library(
    name = "decorators",
    srcs = ["decorators.py"],
    imports = ["../.."],
    visibility = ["//multiplexer/mxlog:__pkg__"],
)
