# Preprocessor helper headers.
cc_library(
    name = "common",
    hdrs = ["common.h"],
    visibility = [
        "//lib:__subpackages__",
        "//mxcontrol:__pkg__",
    ],
)

cc_library(
    name = "kwargs",
    hdrs = ["kwargs.h"],
    visibility = ["//lib:__subpackages__"],
)
