# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\x12\tinference"\x1d\n\x0cInferRequest\x12\r\n\x05image\x18\x01 \x01(\x0c"V\n\rInferResponse\x12\r\n\x05label\x18\x01 \x01(\x05\x12\x15\n\rprobabilities\x18\x02 \x03(\x02\x12\x0e\n\x06worker\x18\x03 \x01(\t\x12\x0f\n\x07seconds\x18\x04 \x01(\x02\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _INFERREQUEST._serialized_start = 30
    _INFERREQUEST._serialized_end = 59
    _INFERRESPONSE._serialized_start = 61
    _INFERRESPONSE._serialized_end = 147
# @@protoc_insertion_point(module_scope)
