"""Writes make/sources.mk, the source lists the Makefile builds from, by
asking Bazel which files the shipped targets are made of. Run by
./format.sh, so the lists follow the BUILD files; `--check` fails when the
committed file is stale, the way the generated docs do.

The Makefile itself is written by hand: the generated protocol buffer
code, the constants, the compiler flags and the layout of build/ are the
same for every source list, only the lists change.
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "make", "sources.mk")

# What ships: the multiplexer with every subcommand, the Python extension,
# and the C++ test roles' Event proto, which the testing package needs.
SHIPPED = "//mxcontrol:mxcontrol_with_debug_symbols + //multiplexer:_native_with_debug_symbols.so"
PYTHON_PACKAGE = (
    "//multiplexer:servers + //multiplexer:clients + //multiplexer:threaded_client_py + //multiplexer:recording"
    " + //multiplexer/testing:testing + //multiplexer/mxlog:streaming + //multiplexer/util:decorators"
    " + //multiplexer/util:timer"
)
# Python tests that need Bazel's runfiles layout and mean nothing outside it.
NOT_OUTSIDE_BAZEL = {"multiplexer/testing/config_test.py"}


def query(expression: str) -> list[str]:
    """Source files matching `expression`, as workspace-relative paths, sorted."""
    result = subprocess.run(
        ["bazel", "query", "--noshow_progress", "--noshow_loading_progress", expression, "--output=label"],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    paths = []
    for label in result.stdout.split():
        package, _, name = label.partition(":")
        paths.append((package[2:] + "/" + name) if package != "//" else name)
    return sorted(set(paths))


def ours(expression: str) -> str:
    """`expression` narrowed to the source files of this repository's packages."""
    return 'filter("^//(lib|multiplexer|mxcontrol)[:/]", kind("source file", %s))' % expression


def variable(name: str, values: list[str]) -> str:
    """A make variable spanning lines, one value per line."""
    return "%s := \\\n%s\n" % (name, "".join("  %s \\\n" % value for value in values)) if values else "%s :=\n" % name


def generate() -> str:
    shipped = query(ours("deps(%s)" % SHIPPED))
    tool = query(ours("deps(//multiplexer:generate_constants)"))
    package = query(ours("deps(%s)" % PYTHON_PACKAGE))
    cc_tests = query("labels(srcs, kind(cc_test, //lib/... + //multiplexer/...))")
    py_tests = [
        path for path in query("labels(srcs, kind(py_test, //multiplexer/...))") if path not in NOT_OUTSIDE_BAZEL
    ]

    def sources(paths, prefixes, exclude=()):
        return [p for p in paths if p.endswith(".cc") and p.startswith(prefixes) and p not in exclude]

    out = [
        "# Generated by make/generate_sources.py from the BUILD files; do not edit.",
        "# Regenerate with ./format.sh.",
        "",
        "# The C++ library a program links: lib/ and multiplexer/, without the",
        "# tool and the Python extension.",
        variable(
            "LIB_SRCS",
            sources(
                shipped,
                ("lib/", "multiplexer/"),
                exclude={"multiplexer/_native.cc", "multiplexer/generate_constants.cc"},
            ),
        ),
        "# The multiplexer binary and its subcommands.",
        variable("MXCONTROL_SRCS", sources(shipped, ("mxcontrol/",))),
        "# What generate_constants needs; none of it depends on the constants it generates.",
        variable("GENERATE_CONSTANTS_SRCS", sources(tool, ("lib/", "multiplexer/"))),
        "# Every header, for `make install`.",
        variable("HEADERS", [p for p in shipped if p.endswith(".h")]),
        "# Every protocol buffer file, of the binaries and of the Python package.",
        variable("PROTOS", sorted(p for p in set(shipped) | set(package) if p.endswith(".proto"))),
        "# The Python package, without the generated modules.",
        variable("PY_FILES", [p for p in package if p.endswith(".py") and not p.endswith("gen_type_id_constants.py")]),
        "# Unit tests: one binary per C++ test file, one unittest module per Python one.",
        variable("CC_TEST_SRCS", cc_tests),
        variable("PY_TEST_FILES", py_tests),
    ]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    text = generate()
    if "--check" in argv:
        current = open(OUTPUT).read() if os.path.exists(OUTPUT) else ""
        if current != text:
            print("stale, run ./format.sh: make/sources.mk")
            return 1
        return 0
    with open(OUTPUT, "w") as output:
        output.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
