# Generated by make/generate_sources.py from the BUILD files; do not edit.
# Regenerate with ./format.sh.

# The C++ library a program links: lib/ and multiplexer/, without the
# tool and the Python extension.
LIB_SRCS := \
  lib/assertion.cc \
  lib/core_dump.cc \
  lib/exception.cc \
  lib/fork.cc \
  lib/kwargs.cc \
  lib/logging/logging.cc \
  lib/memory.cc \
  lib/random.cc \
  lib/release.cc \
  multiplexer/backend/base_multiplexer_server.cc \
  multiplexer/basic_client.cc \
  multiplexer/client.cc \
  multiplexer/connections_manager.cc \
  multiplexer/io/raw_message.cc \
  multiplexer/recorder.cc \
  multiplexer/server.cc \
  multiplexer/threaded_client.cc \


# The multiplexer binary and its subcommands.
MXCONTROL_SRCS := \
  mxcontrol/driver.cc \
  mxcontrol/dump_recording.cc \
  mxcontrol/help.cc \
  mxcontrol/main.cc \
  mxcontrol/receive_logs.cc \
  mxcontrol/recording_control.cc \
  mxcontrol/start_multiplexer_server.cc \
  mxcontrol/stream_logs.cc \
  mxcontrol/task.cc \
  mxcontrol/tasks_holder.cc \


# What generate_constants needs; none of it depends on the constants it generates.
GENERATE_CONSTANTS_SRCS := \
  lib/assertion.cc \
  lib/exception.cc \
  lib/logging/logging.cc \
  lib/random.cc \
  lib/release.cc \
  multiplexer/generate_constants.cc \


# Every header, for `make install`.
HEADERS := \
  lib/assertion.h \
  lib/core_dump.h \
  lib/encoding/base_decoder.h \
  lib/encoding/base_encoder.h \
  lib/encoding/decode_from_range.h \
  lib/encoding/encode_to_range.h \
  lib/encoding/little_endian.h \
  lib/exception.h \
  lib/fd.h \
  lib/fork.h \
  lib/functors.h \
  lib/initialization.h \
  lib/intrusive_value.h \
  lib/kwargs.h \
  lib/logging/impl.h \
  lib/logging/log_tokens.h \
  lib/logging/logging.h \
  lib/memory.h \
  lib/mutex.h \
  lib/preproc/common.h \
  lib/preproc/create_message.h \
  lib/preproc/create_message_detail.h \
  lib/preproc/kwargs.h \
  lib/program.h \
  lib/protobuf/stream.h \
  lib/random.h \
  lib/release.h \
  lib/repr.h \
  lib/sha1.h \
  lib/spanset.h \
  lib/thread_annotations.h \
  lib/thread_checker.h \
  lib/timer.h \
  lib/triple.h \
  lib/type_utils.h \
  lib/vector.h \
  multiplexer/backend/base_multiplexer_server.h \
  multiplexer/basic_client.h \
  multiplexer/client.h \
  multiplexer/config.h \
  multiplexer/connections_manager.h \
  multiplexer/defaults.h \
  multiplexer/io/connection.h \
  multiplexer/io/raw_message.h \
  multiplexer/recorder.h \
  multiplexer/server.h \
  multiplexer/threaded_client.h \
  mxcontrol/driver.h \
  mxcontrol/help.h \
  mxcontrol/start_multiplexer_server.h \
  mxcontrol/task.h \
  mxcontrol/tasks_holder.h \


# Every protocol buffer file, of the binaries and of the Python package.
PROTOS := \
  lib/logging/Logging.proto \
  multiplexer/Multiplexer.proto \
  multiplexer/Recording.proto \
  multiplexer/testing/events.proto \


# The Python package, without the generated modules.
PY_FILES := \
  multiplexer/clients.py \
  multiplexer/mxclient.py \
  multiplexer/mxlog/__init__.py \
  multiplexer/mxlog/streaming.py \
  multiplexer/protocolbuffers.py \
  multiplexer/recording.py \
  multiplexer/release.py \
  multiplexer/servers.py \
  multiplexer/testing/__init__.py \
  multiplexer/testing/fakes.py \
  multiplexer/testing/raw_peer.py \
  multiplexer/threaded_client.py \
  multiplexer/util/decorators.py \
  multiplexer/util/timer.py \


# Unit tests: one binary per C++ test file, one unittest module per Python one.
CC_TEST_SRCS := \
  lib/kwargs_test.cc \
  lib/thread_checker_test.cc \
  multiplexer/backend/serve_thread_test.cc \
  multiplexer/fork_test.cc \
  multiplexer/recorder_test.cc \
  multiplexer/soak_test.cc \
  multiplexer/threaded_client_test.cc \


PY_TEST_FILES := \
  multiplexer/fork_test.py \
  multiplexer/interpreter_exit_test.py \
  multiplexer/leak_test.py \
  multiplexer/mxlog_test.py \
  multiplexer/no_connection_test.py \
  multiplexer/pickle_test.py \
  multiplexer/serve_thread_test.py \
  multiplexer/testing/fakes_test.py \
  multiplexer/threaded_client_py_test.py \

